treewide: compilation fixes for LTS v6.6
Merge of keystone/android-mainline-keystone-qcom-release.6.6.0 (e624619)
into presil-sun triggers below compilation errors. This change is fixing
all of them:

  These symbols are missing from the symbol list and are not available at runtime for unsigned modules:
    generic_hwtstamp_get_lower required by ['8021q.ko']
    generic_hwtstamp_set_lower required by ['8021q.ko']
    memcpy_and_pad required by ['bluetooth.ko']
    overflowgid required by ['bluetooth.ko']
    pid_vnr required by ['bluetooth.ko']
    register_net_sysctl_sz required by ['ieee802154_6lowpan.ko', 'tipc.ko']
    security_release_secctx required by ['bluetooth.ko']
    security_secid_to_secctx required by ['bluetooth.ko']

  drivers/hwtracing/coresight/coresight-core.c:2003:7: error: call to undeclared function 'of_property_read_string'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]

  drivers/mmc/host/sdhci-msm.c:5238:3: error: void function 'sdhci_msm_remove' should not return a value [-Wreturn-type]
  drivers/remoteproc/qcom_common.c:184:53: error: use of undeclared identifier 'MD_SS_ENCR_DONE'

  drivers/rpmsg/qcom_glink_native.c:275:9: error: 'NATIVE_DTR_SIG' macro redefined [-Werror,-Wmacro-redefined]

  drivers/soc/qcom/llcc-qcom.c:1557:6: error: call to undeclared function 'of_platform_populate'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]

  drivers/soc/qcom/qcom_aoss.c:259:65: error: use of undeclared identifier 'data'
  drivers/soc/qcom/qcom_aoss.c:269:14: error: use of undeclared identifier 'data'
  drivers/soc/qcom/qcom_aoss.c:273:66: error: use of undeclared identifier 'data'

  drivers/soc/qcom/wcd939x-i2c.c:1711:3: error: field designator 'probe_new' does not refer to any field in type 'struct i2c_driver'

  drivers/spi/spi-msm-geni.c:104:9: error: 'SE_GENI_CFG_SEQ_START' macro redefined [-Werror,-Wmacro-redefined]

  include/linux/soc/qcom/geni-se.h:143:9: error: 'START_TRIGGER' macro redefined [-Werror,-Wmacro-redefined]

Change-Id: I2f88dd624d2430b4a93d4887fe1ffe13b88d73e9
Signed-off-by: Blagovest Kolenichev <quic_c_bkolen@quicinc.com>
Signed-off-by: Tyler J. Stachecki <stachecki.tyler@gmail.com>